feat: init gitpod config
freeCodeCamp/boilerplate-port-scanner pull request #6
Opened 2024-02-07 11:03 UTC by scissorsneedfoodtoo

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/53470

2024-02-09 08:04 UTC, ShaunSHamilton requested changes
When testing I came across this when first running `python main.py`, but am not sure if we specifically want to leave it as is for Campers to fix:

```bash
Traceback (most recent call last):
  File "/workspace/boilerplate-port-scanner/main.py", line 14, in <module>
    ports = port_scanner.get_open_ports("104.26.10.78", [440, 450], True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_open_ports() takes 2 positional arguments but 3 were given
```

I added `verbose = False` to the `get_open_ports` function def, but Campers can do this too based on the instructions on `/learn`.

```bash
Traceback (most recent call last):
  File "/workspace/boilerplate-port-scanner/main.py", line 15, in <module>
    print(ports + '\n')
          ~~~~~~^~~~~~
TypeError: can only concatenate list (not "str") to list
```

I do not know if this fixes itself if the output is correct, but then I would change the body of the function to not return `[]` off the bat.

2024-02-09 08:04 UTC, ShaunSHamilton commented on .gitpod.yml
> +
```suggestion
```

2024-02-13 06:51 UTC, scissorsneedfoodtoo commented
That's a good point. I caught that during my testing, too.

I don't see any issue in adding `verbose = False` to the definition of the `get_open_ports` function. We already have the other parameters there, so adding an optional third parameter shouldn't be a problem.

For the other lines that throw errors in `main.py`, those do go away if you return a string when the third argument is `True`. But I think we can make things a bit more flexible by changing `print(ports + '\n')` to `print(ports, '\n')`, which shouldn't error out when a list is returned instead of a string.

We could also add newlines after the first couple of `print` statements in `main.py` to make the output look a bit nicer.

2024-02-13 07:09 UTC, ShaunSHamilton approved these changes

2024-02-14 14:25 UTC, merged